### ISSUE TITLE
Saudi data request

### ISSUE THREAD

**Issue by harubi** [justinelliotmeyers/official_saudi_data_dump#1]
Hey,

Amazing job on this data set! Can you please try to get the data on [National Address](https://maps.address.gov.sa/Home/Index?lang=en)? It's an ESRI server with literally every thing in Saudi Arabia. Of what I can gather myself, most of the data is sent as _.pbf_

I tried downloading couple of files and opened them in QGIS: 
<img width="897" alt="Screen Shot 2021-01-27 at 8 33 39 AM" src="https://user-images.githubusercontent.com/936636/105947591-6ca59680-607a-11eb-82e2-47dcab442d36.png">

And they include everything. I really love the work you submitted to OpenAddresses, but street names are points, and the addresses are not polygons that encapsulate individual buildings.

When playing around with QGIS, it exactly represents what they have on the website, with street names and all:
<img width="1552" alt="Screen Shot 2021-01-27 at 8 39 33 AM" src="https://user-images.githubusercontent.com/936636/105948072-5a782800-607b-11eb-9893-70d485de4359.png">

But there is an issue where (I think, if I'm not mistaken) Arabic data only comes from the Arabic interface and vice versa for the English data.

I would extremely appreciate it if you can get the data from it, or share the script you use, it's literally a goldmine 😃

**Comment by justinelliotmeyers** [comment]
I have a copy of the polygons - I don't know if it is a English or Arabic version, I would have to check. I had a colleague assist me with the OA project and it took over a month to complete. All layers besides the buildings are easy, do you have those completed? As per the building data, I will have to find where that is and see what version it is. Like I said a colleague helped me with the full dataset - I can assist with individual aois, but a full country extraction is a massive process.  Let me know what datasets you have, and if you need a specific area - I will look for my full poly version. Talk soon, hope I can assist.

**Comment by harubi** [comment]
That's great! I would appreciate it if you could upload the polygon data!

I know it's a massive effort, I'm trying to write a python script where it downloads every _.pbf_ file on the website, but – due to my embarrassing knowledge of GIS – I couldn't get them to align correctly. I need to figure how to do that. I'm trying to get extract the whole country, and learning how to do that along the way.

The biggest issue for me is knowing what _.pbf_ filenames to request (because there is no obvious pattern on how they're names), how do they align correctly.

What I'm looking for really, is **correct building** and **street data**. Alongside with the zip code data, cities, and localities, which you provided generously, so thank you so much for that!

If it's okay, can you tell me how did you get the data? Am I missing something here?

**Comment by harubi** [comment]
Hey,

Just wondering if you have addresses and streets polygons and are able to upload them? 

I would greatly appreciate it!

**Comment by harubi** [comment]
Thanks anyways!
